### PR TITLE
TUM-9 Command and query for Behaviour entity

### PR DESCRIPTION
**Pull request by guustek**

### CODE REVIEW

**Review by Camed — COMMENTED** [review]
As we have talked yesterday, I guess we should move away from using _IApplicationDbContext_ interface in application layer (as it forces dependency on EF here - and we don't want this). We generally need a little bit of refactoring of our architecture structure which still needs to be discussed.

**Comment by guustek** [comment]
> As we have talked yesterday, I guess we should move away from using _IApplicationDbContext_ interface in application layer (as it forces dependency on EF here - and we don't want this). We generally need a little bit of refactoring of our architecture structure which still needs to be discussed.

**Comment by guustek** [comment]
> As we have talked yesterday, I guess we should move away from using _IApplicationDbContext_ interface in application layer (as it forces dependency on EF here - and we don't want this). We generally need a little bit of refactoring of our architecture structure which still needs to be discussed.

Will adjust that once the repository abstraction is done.

**Review by Camed — APPROVED** [review]
🤙🤙🤙

**Pull request merged**
